// sms-service.js (formerly moolre-service.js)
// Safe pure-client utilities and secure backend proxy calls for TrustLink Escrow.

/**
 * Normalizes a Ghanaian phone number to international format (233XXXXXXXXX) or local 10-digit format.
 * Accepts "055 123 4567", "+233551234567", "0551234567" etc.
 * @param {string} phone - The phone number in any common format.
 * @returns {string} Digits-only phone string.
 */
export function normalizePhone(phone) {
    let p = String(phone || '').replace(/[^0-9]/g, '');
    if (p.startsWith('0')) p = '233' + p.slice(1);
    return p;
}

/**
 * Standard 10-digit local format (e.g. 0551234567).
 */
export function formatGhanaPhoneNumber(phone) {
    let digits = String(phone || '').replace(/[^\d]/g, '');
    if (digits.startsWith('233') && digits.length === 12) {
        return '0' + digits.slice(3);
    }
    if (!digits.startsWith('0') && digits.length === 9) {
        return '0' + digits;
    }
    return digits;
}

/**
 * Formats currency in Ghana Cedis (GH₵).
 */
export function formatCurrency(amount) {
    const num = parseFloat(amount) || 0;
    return `GH₵ ${num.toFixed(2)}`;
}

/**
 * Splits the platform fee between buyer and seller based on the escrow's
 * fee allocation ('buyer' | 'seller' | 'split').
 * Buyer pays: amount + buyerFee. Seller receives: amount - sellerFee.
 * @returns {{ totalFee: number, buyerFee: number, sellerFee: number, buyerTotal: number, sellerNet: number }}
 */
export function computeFeeSplit(amount, feePercent = 1.5, allocation = 'split') {
    const amt = parseFloat(amount) || 0;
    const pct = (parseFloat(feePercent) || 0) / 100;
    const totalFee = Math.round(amt * pct * 100) / 100;
    let buyerFee = 0, sellerFee = 0;
    if (allocation === 'buyer') buyerFee = totalFee;
    else if (allocation === 'seller') sellerFee = totalFee;
    else {
        buyerFee = Math.round(totalFee / 2 * 100) / 100;
        sellerFee = Math.round((totalFee - buyerFee) * 100) / 100;
    }
    return {
        totalFee,
        buyerFee,
        sellerFee,
        buyerTotal: Math.round((amt + buyerFee) * 100) / 100,
        sellerNet: Math.round((amt - sellerFee) * 100) / 100
    };
}

/**
 * Generates a cryptographically random hex token (for one-time links).
 * @param {number} bytes - Number of random bytes (default 16 = 32 hex chars).
 */
export function generateSecureToken(bytes = 16) {
    const arr = new Uint8Array(bytes);
    crypto.getRandomValues(arr);
    return Array.from(arr, b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * SHA-256 hash of a string, returned as hex.
 */
export async function sha256Hex(text) {
    const data = new TextEncoder().encode(text);
    const digest = await crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(digest), b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Best-effort extraction of a user's phone number from profile data.
 */
export function pickUserPhone(userData) {
    if (!userData) return "";
    if (userData.phone) return userData.phone;
    const oi = String(userData.originalIdentifier || '');
    if (/^[+0-9 ()-]{9,}$/.test(oi)) return oi;
    return "";
}

/**
 * Sends a phone verification OTP via server-side SMS gateway (SasuSync / Arkesel).
 * @param {string} phone - Target phone number
 * @param {string} [customOtp] - Optional custom OTP code (e.g. 4-digit generated by client)
 */
export async function sendVerificationOTP(phone, customOtp = "") {
    try {
        const msg = customOtp 
            ? `Your TrustLink verification code is: ${customOtp}. Valid for 5 minutes.`
            : `Your TrustLink verification code. Valid for 5 minutes.`;
        const res = await sendEscrowStatusSMS(phone, msg, `otp-${Date.now()}`);
        return {
            status: res.success ? 1 : 0,
            message: res.success ? "Verification OTP dispatched successfully." : (res.error || "Failed to dispatch OTP.")
        };
    } catch (err) {
        return { status: 0, message: "Network error requesting verification code." };
    }
}
// Retain alias for backward compatibility
export const sendMoolreOTP = sendVerificationOTP;

/**
 * Sends transactional SMS notifications to users via server-side SMS gateway.
 */
export async function sendEscrowStatusSMS(phone, message, referenceId = "") {
    try {
        const response = await fetch("/api/v1/sms/send", {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ phone, message, referenceId })
        });
        const data = await response.json().catch(() => ({}));
        return { success: response.ok, data };
    } catch (err) {
        console.warn("SMS send network error:", err);
        return { success: false, error: err.message };
    }
}

/**
 * High-level SMS notification dispatcher with fallback and details support.
 */
export async function sendSMSNotification(phone, checkoutUrl, escrowId, customMessage = "", smsDetails = {}) {
    const formattedAmount = Number(smsDetails.amount || 0).toFixed(2);
    const orderTitle = smsDetails.description || 'Order';
    const seller = smsDetails.sellerName || 'TrustLink User';
    const msg = customMessage || `TrustLink: ${seller} created an escrow for ${orderTitle} (GH₵ ${formattedAmount}). Pay securely at: ${checkoutUrl}`;
    return sendEscrowStatusSMS(phone, msg, `${escrowId}-create`);
}

/**
 * Dispatches an automated WhatsApp payment request & checkout link to a customer via Meta WhatsApp Cloud API.
 */
export async function sendWhatsAppNotification({ to, description, amount, sellerName, checkoutUrl, escrowId }) {
    try {
        const response = await fetch("/api/send-whatsapp", {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ to, description, amount, sellerName, checkoutUrl, escrowId })
        });
        const data = await response.json();
        if (!response.ok) {
            console.warn("WhatsApp dispatch notice:", data.error || data);
            return { success: false, error: data.error, details: data.details };
        }
        return { success: true, messageId: data.messageId };
    } catch (err) {
        console.warn("WhatsApp notification network error:", err);
        return { success: false, error: err.message };
    }
}


